import 'package:flutter/material.dart';

import 'package:network_api/homepage_dart.dart';
import 'package:network_api/service/user_service.dart';

import 'model/employee_model.dart';
import 'model/user_model.dart';


class AlbumDisplay extends StatefulWidget {
  @override
  _AlbumDisplayState createState() => _AlbumDisplayState();
}

class _AlbumDisplayState extends State<AlbumDisplay> {
  // Future <Album> futureAlbum;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    // futureAlbum = fetchAlbum();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('JSON ListView in Flutter'),
      ),
      body: FutureBuilder<List<Autogenerated>>(
        future: fetchJSONData(),
        builder: (context, snapshot) {
 
          if (!snapshot.hasData) return Center(child: CircularProgressIndicator());
 
          return ListView(
            children: snapshot.data
            .map((user) => ListTile(
                  title: Text(user.name),
                  onTap: (){ 
                    Navigator.push(context,MaterialPageRoute(builder: (context)=>Employ()));
                  },
                  subtitle: Text(user.email),
                  leading: CircleAvatar(
                    backgroundColor: Colors.green,
                    child: Text(user.name[0],
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20.0,
                    )),
                  ),
                ),
              )
            .toList(),
          );
        },
      ),
    );
 
  }
}